#Postres monitoring
- job_name: 'Postgres_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['POSTGRES_SERVER_IP:9187']
    
- job_name: 'Node_exporter_postgres'
    scrape_interval: 5s
    static_configs:
      - targets: ['POSTGRES_SERVER_IP:9100']
